import Head from 'next/head'
import Navbar from '@/components/Header'
import Carousel from '@/components/Carousel'
import OneProduct from '@/components/Products'
import Parallax from '@/components/Parallax'
import Social from '@/components/Social'


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Mern.png" />
      </Head>
      <Navbar />
      <div>
        <Carousel />
        <OneProduct />
        <Parallax />
        <Social />
      </div>

    </>
  )
}
